// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whcpcqcesigjczcxxiwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY3BjcWNlc2lnamN6Y3h4aXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzMwMDQsImV4cCI6MjA2NTU0OTAwNH0.cZmez8B1_-QRk7EtSlm-KPw8vDwpxo8gRtnZ_Vd60Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);